### ISSUE TITLE
Publication dates prior to 1901-12-13 get set to 01-01-1970 upon saving 

### ISSUE THREAD

**Issue by clq** [nosegraze/book-database#148]
Probably due to the limitations of Unix time, and perhaps not fixable, but currently dates prior to December of 1901 seem to not be supported.

Repro:
Edit any book in the book library
Set the Publication Date to e.g. January 1, 1868
Save
Publication date is now January 1, 1970

**Comment by clq** [comment]
Actually, I appear to be running a 32-bit version of MySql. With a 64 bit version this wouldn't have been a problem...

**Comment by clq** [comment]
Aaaaand, just saw that this has been addressed recently by changing datetime to date. Let's see if I can change the type of the field in my existing DB.

https://github.com/nosegraze/book-database/commit/32d328d9bdbc3c129c84a219a2fc0f990fc5677d#diff-1a82c140bd9faf9ccc670472a3e70cd2

**Comment by clq** [comment]
Actually, even after migrating, with the type being date and the DB containing the correct value, the wrong date is displayed when fetching the date.

Repro:
In the DB set the pub_date of any book to before 1901
Open the book in the library
The publication date is displayed as 01-01-1970

**Comment by nosegraze** [comment]
Confirmed it's a limitation with 32-bit. I've added a new Requirements section to the readme, which mentions this: https://github.com/nosegraze/book-database/blob/master/README.md#requirements
