### ISSUE TITLE
Analytics: "read not reviewed" query references column that no longer exists in the schema

### ISSUE THREAD

**Issue by clq** [nosegraze/book-database#154]
https://github.com/nosegraze/book-database/blob/92ca5f4936ebb5d4e23d2ea5eff9d970c24df2cc/includes/class-analytics.php#L653

It probably needs an update to use the reviews-table instead.

**Comment by nosegraze** [comment]
Good catch - thank you!

**Comment by clq** [comment]
PR resolves the problem for me in the scenario where it was previously failing (fresh installation).
