### ISSUE TITLE
Series position input field no longer supports floating-point values

### ISSUE THREAD

**Issue by clq** [nosegraze/book-database#174]
Running on commit https://github.com/nosegraze/book-database/commit/8f1f5574f94634efdc5eb08c719aebe43d859c5b:

Adding a floating point position-in-series value in the web-interface, say 0.5, stores the value in the DB as 0.

Any currently existing books with a position in series value of x.y is set to x when the entry is saved through the web-interface.

**Comment by nosegraze** [comment]
PR: #178

Fixes the problem and I also added unit tests to watch for this kind of thing in the future.
