### ISSUE TITLE
Auto-population of "Date Published" in review appears to be wrong when server timezone doesn't match blog timezone

### ISSUE THREAD

**Issue by clq** [nosegraze/book-database#198]
Might well be a user-problem, and I'm wondering whether this might be due to an inappropriate usage of blog timezone settings, or a problem with Wordpress functions, but filing an issue anyway in case it's something that's of interest: 

Server time: UTC
Blog timezone (as set in general Wordpress settings): UTC+1

When associating a review with a post published at 3pm the associated bdb-reviews page is auto-populated with a published date of 4pm.

This leads to any review associated with a post published "now" showing up for an hour as "Review coming <date>" in the book grid, before the review shows up as being published, even though the post has been published on the blog.

My (rather uneducated) guess is that is might be happening here: https://github.com/nosegraze/book-database/blob/4fd65464867324464efae22a997ccf327977f97a/includes/admin/reviews/review-actions.php#L39

...and that $_POST['date_published'] and/or get_gmt_from_date doesn't work as intended when the Wordpress-timezone doesn't match that of the server.

**Comment by nosegraze** [comment]
If you're syncing the publish date with the post then I think the problem is actually here: https://github.com/nosegraze/book-database/blob/master/includes/reviews/review-actions.php#L43

Does it work if you change that line to:

```php
$post_date = date( 'Y-m-d H:i:s', strtotime( $post->post_date_gmt ) );
```

**Comment by clq** [comment]
Yup, that fixed it!
