### ISSUE TITLE
Book-grid: "Read Review" link disappears from all book entries when unread books appear in the grid

### ISSUE THREAD

**Issue by clq** [nosegraze/book-database#200]
The following:

[book-grid reviews-only="1" show-ratings="1" show-review-link="1" author="Stephen King"]

Gives:

![bilde](https://user-images.githubusercontent.com/814888/74153693-79cf3880-4c11-11ea-8643-7050913776fb.png)

But when setting reviews-only to 0, like:

[book-grid reviews-only="0" show-ratings="1" show-review-link="1" author="Stephen King"]

...which causes Elevation to also appear in the screenshot, the "Read Review" link has disappeared from all entries, even the ones with reviews.

![bilde](https://user-images.githubusercontent.com/814888/74153808-ab480400-4c11-11ea-80a9-c6d9ac285eac.png)

**Comment by nosegraze** [comment]
PR: #201
