### ISSUE TITLE
Interactive drop-down menu for Publisher in [book-reviews] appears to only show first 50 Publishers

### ISSUE THREAD

**Issue by clq** [nosegraze/book-database#222]
As in title, in the interactive search provided by [book-reviews], the list is sorted alphabetically, and cuts off at 50 entries (not including "Any).

**Comment by nosegraze** [comment]
Increased limit to 300.

At some point it might be worth considering some other type of selection method if there are such a large amount. Dropdowns lose their usefulness if there are too many options, unless you know exactly what you're looking for, in which case an auto-suggesting text box or similar might be preferable.
